#main#
##nameof##
nameof_main: minetime
nameof_logo: §3minetime_logo:§b>
nameof_loge: §4minetime_loge:§c>
nameof_cluster: "unit0"
nameof_database: "room0"
nameof_collection: "chest0"
nameof_connection: "mongodb://keeper:db9314671364@unit0-shard-00-00.19rj5.mongodb.net:27017,unit0-shard-00-01.19rj5.mongodb.net:27017,unit0-shard-00-02.19rj5.mongodb.net:27017/mdbstore?ssl=true&replicaSet=atlas-94hogs-shard-0&authSource=admin&retryWrites=true&w=majority"
#nameof_connection:
#  - "mongodb://keeper:db9314671364@"
#  - "unit0-shard-00-00.19rj5.mongodb.net:27017,"
#  - "unit0-shard-00-01.19rj5.mongodb.net:27017,"
#  - "unit0-shard-00-02.19rj5.mongodb.net:27017"
#  - "/mdbstore?"
#  - "ssl=true"
#  - "&replicaSet=atlas-94hogs-shard-0"
#  - "&authSource=admin"
#  - "&retryWrites=true"
#  - "&w=majority"
##sizeof##
#endf#